spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
alpha:
  vantage:
    url: https://www.alphavantage.co/query
    key: 1PA3VZKFACQRRVMA

feign:
  client:
    config:
      default:
        loggerLevel: full

indicator:
  ema:
    threshold: 0.05
  rsi:
    columnsNumber: 3
  macd:
    columnsNumber: 3