spring:
  elasticsearch:
    rest:
      uris: localhost:9200
      username: stockAdmin
      password: $tockAdm!n
notifier:
  url: localhost:8070
alpha:
  vantage:
    url: https://www.alphavantage.co/query
    key: 1PA3VZKFACQRRVMA

feign:
  client:
    config:
      default:
        loggerLevel: full

indicator:
  ema:
    threshold: 0.05
  rsi:
    columnsNumber: 3
  macd:
    columnsNumber: 3