server:
  shutdown: graceful
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
indicator:
  ema:
    threshold: 0.03
  rsi:
    columnsNumber: 3
  macd:
    columnsNumber: 2

tinkoff:
  api:
    url: https://api-invest.tinkoff.ru/openapi
alpha:
  vantage:
    url: https://www.alphavantage.co/query
    key: 1PA3VZKFACQRRVMA
twelvedata:
  api:
    url: https://api.twelvedata.com
    key:
      - b7e76a8b950e427daafdf6d939e4dd82
      - 45cdc790f12540cabc0efdfa07e799dc
      - 65901c0f82324bdc84816468b2aa0838

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    url: jdbc:mysql://localhost:3307/screener?allowPublicKeyRetrieval=true
    username: root
    password: j&4>TqA2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    database: mysql
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: screener

telegram:
  bot:
    token: 5201133570:AAGYX-X2cEDT0B5TIN1Y7xdT70H5xBgQNek
    username: screener_test_bot

screener:
  pattern:
    cron: 0 20 15 * * MON-FRI
  level:
    candle-number: 210
    cron: 0 0 7 * * SAT