sandbox.url.stocks=https://api-invest.tinkoff.ru/openapi/sandbox/market/stocks
sandbox.url.stockByTicker=https://api-invest.tinkoff.ru/openapi/sandbox/market/search/by-ticker
sandbox.url.candesByFigi=https://api-invest.tinkoff.ru/openapi/sandbox/market/candles
token=t.pFGWIbIK0_H5k1dQCR1XQ86vayy96VMNgpa4aPTIYn0h-0oJc_V93nTciBOTID_RdJ7MbqHiZmcoR_5vRZmlFg

