insert into stocks_to_scan(id, figi, ticker, name) values (1, null, 'SPGI', 'S&P Global Inc.');
insert into stocks_to_scan(id, figi, ticker, name) values (2, null, 'MCO', 'Moody’s Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (3, null, 'CPRT', 'Copart, Inc.');
insert into stocks_to_scan(id, figi, ticker, name) values (4, null, 'EFX', 'Equifax, Inc.');
insert into stocks_to_scan(id, figi, ticker, name) values (5, null, 'FLT', 'FleetCor Technologies, Inc.');
insert into stocks_to_scan(id, figi, ticker, name) values (6, null, 'CRL', 'Charles River Laboratories International, Inc.');
insert into stocks_to_scan(id, figi, ticker, name) values (7, null, 'OMC', 'Omnicom Group Inc.');
insert into stocks_to_scan(id, figi, ticker, name) values (8, null, 'IPG', 'Interpublic Group of Companies, Inc. (The)');
insert into stocks_to_scan(id, figi, ticker, name) values (9, null, 'RHI', 'Robert Half International Inc.');
insert into stocks_to_scan(id, figi, ticker, name) values (10, null, 'NLSN', 'Nielsen N.V.');
insert into stocks_to_scan(id, figi, ticker, name) values (11, null, 'VZ', 'Verizon Communications Inc.');
insert into stocks_to_scan(id, figi, ticker, name) values (12, null, 'T', 'AT&T');
insert into stocks_to_scan(id, figi, ticker, name) values (13, null, 'TMUS', 'T-Mobile US');
insert into stocks_to_scan(id, figi, ticker, name) values (14, null, 'LUMN', 'Lumen Technologies,');
insert into stocks_to_scan(id, figi, ticker, name) values (15, null, 'TSLA', 'Tesla');
insert into stocks_to_scan(id, figi, ticker, name) values (16, null, 'F', 'Ford Motor Company');
insert into stocks_to_scan(id, figi, ticker, name) values (17, null, 'GM', 'General Motors Company');
insert into stocks_to_scan(id, figi, ticker, name) values (18, null, 'ATVI', 'Activision Blizzard');
insert into stocks_to_scan(id, figi, ticker, name) values (19, null, 'EA', 'Electronic Arts');
insert into stocks_to_scan(id, figi, ticker, name) values (20, null, 'DHI', 'D.R. Horton');
insert into stocks_to_scan(id, figi, ticker, name) values (21, null, 'SWK', 'Stanley Black & Decker');
insert into stocks_to_scan(id, figi, ticker, name) values (22, null, 'TTWO', 'Take-Two Interactive Software');
insert into stocks_to_scan(id, figi, ticker, name) values (23, null, 'NVR', 'NVR');
insert into stocks_to_scan(id, figi, ticker, name) values (24, null, 'LKQ', 'LKQ Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (25, null, 'PHM', 'PulteGroup');
insert into stocks_to_scan(id, figi, ticker, name) values (26, null, 'WHR', 'Whirlpool Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (27, null, 'HAS', 'Hasbro');
insert into stocks_to_scan(id, figi, ticker, name) values (28, null, 'MHK', 'Mohawk Industries');
insert into stocks_to_scan(id, figi, ticker, name) values (29, null, 'SNA', 'Snap-On');
insert into stocks_to_scan(id, figi, ticker, name) values (30, null, 'PG', 'Procter & Gamble Company');
insert into stocks_to_scan(id, figi, ticker, name) values (31, null, 'NKE', 'Nike');
insert into stocks_to_scan(id, figi, ticker, name) values (32, null, 'KO', 'Coca-Cola Company');
insert into stocks_to_scan(id, figi, ticker, name) values (33, null, 'PEP', 'PepsiCo');
insert into stocks_to_scan(id, figi, ticker, name) values (34, null, 'PM', 'Philip Morris International');
insert into stocks_to_scan(id, figi, ticker, name) values (35, null, 'EL', 'Estee Lauder Companies');
insert into stocks_to_scan(id, figi, ticker, name) values (36, null, 'MDLZ', 'Mondelez International');
insert into stocks_to_scan(id, figi, ticker, name) values (37, null, 'MO', 'Altria Group');
insert into stocks_to_scan(id, figi, ticker, name) values (38, null, 'CL', 'Colgate-Palmolive Company');
insert into stocks_to_scan(id, figi, ticker, name) values (39, null, 'MNST', 'Monster Beverage Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (40, null, 'KMB', 'Kimberly-Clark Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (41, null, 'STZ', 'Constellation Brands');
insert into stocks_to_scan(id, figi, ticker, name) values (42, null, 'KHC', 'The Kraft Heinz Company');
insert into stocks_to_scan(id, figi, ticker, name) values (43, null, 'GIS', 'General Mills');
insert into stocks_to_scan(id, figi, ticker, name) values (44, null, 'HSY', 'The Hershey Company');
insert into stocks_to_scan(id, figi, ticker, name) values (45, null, 'IFF', 'International Flavors & Fragrances');
insert into stocks_to_scan(id, figi, ticker, name) values (46, null, 'BF.B', 'Brown Forman');
insert into stocks_to_scan(id, figi, ticker, name) values (47, null, 'TSN', 'Tyson Foods');
insert into stocks_to_scan(id, figi, ticker, name) values (48, null, 'VFC', 'V.F. Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (49, null, 'HRL', 'Hormel Foods Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (50, null, 'MKC', 'McCormick & Company');
insert into stocks_to_scan(id, figi, ticker, name) values (51, null, 'CHD', 'Church & Dwight Company');
insert into stocks_to_scan(id, figi, ticker, name) values (52, null, 'K', 'Kellogg Company');
insert into stocks_to_scan(id, figi, ticker, name) values (53, null, 'CLX', 'Clorox Company');
insert into stocks_to_scan(id, figi, ticker, name) values (54, null, 'CAG', 'ConAgra Brands');
insert into stocks_to_scan(id, figi, ticker, name) values (55, null, 'SJM', 'J.M. Smucker Company');
insert into stocks_to_scan(id, figi, ticker, name) values (56, null, 'CPB', 'Campbell Soup Company');
insert into stocks_to_scan(id, figi, ticker, name) values (57, null, 'TAP', 'Molson Coors Beverage');
insert into stocks_to_scan(id, figi, ticker, name) values (58, null, 'LW', 'Lamb Weston Holdings');
insert into stocks_to_scan(id, figi, ticker, name) values (59, null, 'UAA', 'Under Armour');
insert into stocks_to_scan(id, figi, ticker, name) values (60, null, 'UA', 'Under Armour');
insert into stocks_to_scan(id, figi, ticker, name) values (61, null, 'PVH', 'PVH Corp.');
insert into stocks_to_scan(id, figi, ticker, name) values (62, null, 'DIS', 'Walt Disney');
insert into stocks_to_scan(id, figi, ticker, name) values (63, null, 'CMCSA', 'Comcast');
insert into stocks_to_scan(id, figi, ticker, name) values (64, null, 'MCD', 'McDonald’s');
insert into stocks_to_scan(id, figi, ticker, name) values (65, null, 'SBUX', 'Starbucks');
insert into stocks_to_scan(id, figi, ticker, name) values (66, null, 'CHTR', 'Charter Communications');
insert into stocks_to_scan(id, figi, ticker, name) values (67, null, 'BKNG', 'Booking Holdings ');
insert into stocks_to_scan(id, figi, ticker, name) values (68, null, 'MAR', 'Marriott');
insert into stocks_to_scan(id, figi, ticker, name) values (69, null, 'CMG', 'Chipotle Mexican Grill');
insert into stocks_to_scan(id, figi, ticker, name) values (70, null, 'CTAS', 'Cintas');
insert into stocks_to_scan(id, figi, ticker, name) values (71, null, 'HLT', 'Hilton Worldwide Holdings');
insert into stocks_to_scan(id, figi, ticker, name) values (72, null, 'YUM', 'Yum! Brands');
insert into stocks_to_scan(id, figi, ticker, name) values (73, null, 'LVS', 'Las Vegas Sands');
insert into stocks_to_scan(id, figi, ticker, name) values (74, null, 'EXPE', 'Expedia');
insert into stocks_to_scan(id, figi, ticker, name) values (75, null, 'LYV', 'Live Nation Entertainment');
insert into stocks_to_scan(id, figi, ticker, name) values (76, null, 'MGM', 'MGM Resorts International');
insert into stocks_to_scan(id, figi, ticker, name) values (77, null, 'VIAC', 'ViacomCBS');
insert into stocks_to_scan(id, figi, ticker, name) values (78, null, 'FOX', 'Fox Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (79, null, 'RCL', 'Royal Caribbean Cruises');
insert into stocks_to_scan(id, figi, ticker, name) values (80, null, 'DPZ', 'Domino’s Pizza');
insert into stocks_to_scan(id, figi, ticker, name) values (81, null, 'CZR', 'Caesars Entertainment');
insert into stocks_to_scan(id, figi, ticker, name) values (82, null, 'DRI', 'Darden Restaurants');
insert into stocks_to_scan(id, figi, ticker, name) values (83, null, 'DISH', 'DISH Network');
insert into stocks_to_scan(id, figi, ticker, name) values (84, null, 'ROL', 'Rollins');
insert into stocks_to_scan(id, figi, ticker, name) values (85, null, 'NWS', 'News Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (86, null, 'DISCA', 'Discovery, Inc');
insert into stocks_to_scan(id, figi, ticker, name) values (87, null, 'WYNN', 'Wynn Resorts');
insert into stocks_to_scan(id, figi, ticker, name) values (88, null, 'NCLH', 'Norwegian Cruise Line');
insert into stocks_to_scan(id, figi, ticker, name) values (89, null, 'PENN', 'Penn National Gaming');
insert into stocks_to_scan(id, figi, ticker, name) values (90, null, 'SYY', 'Sysco');
insert into stocks_to_scan(id, figi, ticker, name) values (91, null, 'MCK', 'McKesson');
insert into stocks_to_scan(id, figi, ticker, name) values (92, null, 'FAST', 'Fastenal');
insert into stocks_to_scan(id, figi, ticker, name) values (93, null, 'ABC', 'AmerisourceBergen');
insert into stocks_to_scan(id, figi, ticker, name) values (94, null, 'GWW', 'W.W. Grainger');
insert into stocks_to_scan(id, figi, ticker, name) values (95, null, 'POOL', 'Pool');
insert into stocks_to_scan(id, figi, ticker, name) values (96, null, 'GPC', 'Genuine Parts');
insert into stocks_to_scan(id, figi, ticker, name) values (97, null, 'CAH', 'Cardinal Health');
insert into stocks_to_scan(id, figi, ticker, name) values (98, null, 'HSIC', 'Henry Schein');
insert into stocks_to_scan(id, figi, ticker, name) values (99, null, 'AAPL', 'Apple');
insert into stocks_to_scan(id, figi, ticker, name) values (100, null, 'NVDA', 'NVIDIA');
insert into stocks_to_scan(id, figi, ticker, name) values (101, null, 'AVGO', 'Broadcom');
insert into stocks_to_scan(id, figi, ticker, name) values (102, null, 'INTC', 'Intel');
insert into stocks_to_scan(id, figi, ticker, name) values (103, null, 'QCOM', 'QUALCOMM');
insert into stocks_to_scan(id, figi, ticker, name) values (104, null, 'AMD', 'Advanced Micro Devices');
insert into stocks_to_scan(id, figi, ticker, name) values (105, null, 'TXN', 'Texas Instruments');
insert into stocks_to_scan(id, figi, ticker, name) values (106, null, 'RTX', 'Raytheon Technologies');
insert into stocks_to_scan(id, figi, ticker, name) values (107, null, 'BA', 'Boeing');
insert into stocks_to_scan(id, figi, ticker, name) values (108, null, 'MU', 'Micron Technology');
insert into stocks_to_scan(id, figi, ticker, name) values (109, null, 'LRCX', 'Lam Research');
insert into stocks_to_scan(id, figi, ticker, name) values (110, null, 'LMT', 'Lockheed Martin');
insert into stocks_to_scan(id, figi, ticker, name) values (111, null, 'ADI', 'Analog Devices');
insert into stocks_to_scan(id, figi, ticker, name) values (112, null, 'KLAC', 'KLA');
insert into stocks_to_scan(id, figi, ticker, name) values (113, null, 'NXPI', 'NXP Semiconductors');
insert into stocks_to_scan(id, figi, ticker, name) values (114, null, 'NOC', 'Northrop Grumman');
insert into stocks_to_scan(id, figi, ticker, name) values (115, null, 'GD', 'General Dynamics');
insert into stocks_to_scan(id, figi, ticker, name) values (116, null, 'XLNX', 'Xilinx');
insert into stocks_to_scan(id, figi, ticker, name) values (117, null, 'FTNT', 'Fortinet');
insert into stocks_to_scan(id, figi, ticker, name) values (118, null, 'TEL', 'TE Connectivity Ltd. New Switzerland Registered Shares');
insert into stocks_to_scan(id, figi, ticker, name) values (119, null, 'APH', 'Amphenol');
insert into stocks_to_scan(id, figi, ticker, name) values (120, null, 'MCHP', 'Microchip Technology');
insert into stocks_to_scan(id, figi, ticker, name) values (121, null, 'MSI', 'Motorola Solutions');
insert into stocks_to_scan(id, figi, ticker, name) values (122, null, 'ANET', 'Arista Networks');
insert into stocks_to_scan(id, figi, ticker, name) values (123, null, 'LHX', 'L3Harris Technologies');
insert into stocks_to_scan(id, figi, ticker, name) values (124, null, 'HPQ', 'HP');
insert into stocks_to_scan(id, figi, ticker, name) values (125, null, 'KEYS', 'Keysight Technologies');
insert into stocks_to_scan(id, figi, ticker, name) values (126, null, 'TDG', 'Transdigm Group');
insert into stocks_to_scan(id, figi, ticker, name) values (127, null, 'GLW', 'Corning Incorporated');
insert into stocks_to_scan(id, figi, ticker, name) values (128, null, 'ZBRA', 'Zebra Technologies');
insert into stocks_to_scan(id, figi, ticker, name) values (129, null, 'TER', 'Teradyne');
insert into stocks_to_scan(id, figi, ticker, name) values (130, null, 'SWKS', 'Skyworks Solutions');
insert into stocks_to_scan(id, figi, ticker, name) values (131, null, 'GRMN', 'Garmin');
insert into stocks_to_scan(id, figi, ticker, name) values (132, null, 'STX', 'Seagate Technology ');
insert into stocks_to_scan(id, figi, ticker, name) values (133, null, 'ENPH', 'Enphase Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (134, null, 'MPWR', 'Monolithic Power Systems');
insert into stocks_to_scan(id, figi, ticker, name) values (135, null, 'TRMB', 'Trimble');
insert into stocks_to_scan(id, figi, ticker, name) values (136, null, 'HPE', 'Hewlett Packard Enterprise');
insert into stocks_to_scan(id, figi, ticker, name) values (137, null, 'TDY', 'Teledyne Technologies ');
insert into stocks_to_scan(id, figi, ticker, name) values (138, null, 'WDC', 'Western Digital ');
insert into stocks_to_scan(id, figi, ticker, name) values (139, null, 'NTAP', 'NetApp');
insert into stocks_to_scan(id, figi, ticker, name) values (140, null, 'QRVO', 'Qorvo');
insert into stocks_to_scan(id, figi, ticker, name) values (141, null, 'TXT', 'Textron');
insert into stocks_to_scan(id, figi, ticker, name) values (142, null, 'FFIV', 'F5');
insert into stocks_to_scan(id, figi, ticker, name) values (143, null, 'HWM', 'Howmet Aerospace');
insert into stocks_to_scan(id, figi, ticker, name) values (144, null, 'IPGP', 'IPG Photonics');
insert into stocks_to_scan(id, figi, ticker, name) values (145, null, 'HII', 'Huntington Ingalls');
insert into stocks_to_scan(id, figi, ticker, name) values (146, null, 'XOM', 'Exxon Mobil');
insert into stocks_to_scan(id, figi, ticker, name) values (147, null, 'CVX', 'Chevron');
insert into stocks_to_scan(id, figi, ticker, name) values (148, null, 'COP', 'ConocoPhillips');
insert into stocks_to_scan(id, figi, ticker, name) values (149, null, 'EOG', 'EOG Resources');
insert into stocks_to_scan(id, figi, ticker, name) values (150, null, 'PXD', 'Pioneer Natural Resources');
insert into stocks_to_scan(id, figi, ticker, name) values (151, null, 'MPC', 'Marathon Petroleum');
insert into stocks_to_scan(id, figi, ticker, name) values (152, null, 'PSX', 'Phillips 66');
insert into stocks_to_scan(id, figi, ticker, name) values (153, null, 'VLO', 'Valero Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (154, null, 'DVN', 'Devon Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (155, null, 'OXY', 'Occidental Petroleum');
insert into stocks_to_scan(id, figi, ticker, name) values (156, null, 'HES', 'Hess');
insert into stocks_to_scan(id, figi, ticker, name) values (157, null, 'FANG', 'Diamondback Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (158, null, 'CTRA', 'Coterra Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (159, null, 'MRO', 'Marathon Oil');
insert into stocks_to_scan(id, figi, ticker, name) values (160, null, 'APA', 'APA Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (161, null, 'TSCO', 'Tractor Supply');
insert into stocks_to_scan(id, figi, ticker, name) values (162, null, 'ETSY', 'Etsy');
insert into stocks_to_scan(id, figi, ticker, name) values (163, null, 'BBY', 'Best Buy Co.');
insert into stocks_to_scan(id, figi, ticker, name) values (164, null, 'ULTA', 'Ulta Beauty');
insert into stocks_to_scan(id, figi, ticker, name) values (165, null, 'KMX', 'CarMax');
insert into stocks_to_scan(id, figi, ticker, name) values (166, null, 'BBWI', 'Bath & Body Works');
insert into stocks_to_scan(id, figi, ticker, name) values (167, null, 'AAP', 'Advance Auto Parts');
insert into stocks_to_scan(id, figi, ticker, name) values (168, null, 'TPR', 'Tapestry');
insert into stocks_to_scan(id, figi, ticker, name) values (169, null, 'RL', 'Ralph Lauren');
insert into stocks_to_scan(id, figi, ticker, name) values (170, null, 'BRK.B', 'Berkshire Hathaway');
insert into stocks_to_scan(id, figi, ticker, name) values (171, null, 'TJX', 'TJX Companies');
insert into stocks_to_scan(id, figi, ticker, name) values (172, null, 'DG', 'Dollar General');
insert into stocks_to_scan(id, figi, ticker, name) values (173, null, 'ORLY', 'O’Reilly Automotive');
insert into stocks_to_scan(id, figi, ticker, name) values (174, null, 'WBA', 'Walgreens Boots Alliance');
insert into stocks_to_scan(id, figi, ticker, name) values (175, null, 'AZO', 'AutoZone');
insert into stocks_to_scan(id, figi, ticker, name) values (176, null, 'EBAY', 'eBay');
insert into stocks_to_scan(id, figi, ticker, name) values (177, null, 'ROST', 'Ross Stores');
insert into stocks_to_scan(id, figi, ticker, name) values (178, null, 'KR', 'Kroger Company');
insert into stocks_to_scan(id, figi, ticker, name) values (179, null, 'DLTR', 'Dollar Tree');
insert into stocks_to_scan(id, figi, ticker, name) values (180, null, 'JPM', 'JP Morgan Chase & Co');
insert into stocks_to_scan(id, figi, ticker, name) values (181, null, 'V', 'Visa');
insert into stocks_to_scan(id, figi, ticker, name) values (182, null, 'BAC', 'Bank of America');
insert into stocks_to_scan(id, figi, ticker, name) values (183, null, 'MA', 'Mastercard');
insert into stocks_to_scan(id, figi, ticker, name) values (184, null, 'WFC', 'Wells Fargo & Company');
insert into stocks_to_scan(id, figi, ticker, name) values (185, null, 'MS', 'Morgan Stanley');
insert into stocks_to_scan(id, figi, ticker, name) values (186, null, 'SCHW', 'Charles Schwab');
insert into stocks_to_scan(id, figi, ticker, name) values (187, null, 'BLK', 'BlackRock');
insert into stocks_to_scan(id, figi, ticker, name) values (188, null, 'AMT', 'American Tower');
insert into stocks_to_scan(id, figi, ticker, name) values (189, null, 'GS', 'Goldman Sachs');
insert into stocks_to_scan(id, figi, ticker, name) values (190, null, 'AXP', 'American Express');
insert into stocks_to_scan(id, figi, ticker, name) values (191, null, 'PLD', 'Prologis');
insert into stocks_to_scan(id, figi, ticker, name) values (192, null, 'C', 'Citigroup');
insert into stocks_to_scan(id, figi, ticker, name) values (193, null, 'CCI', 'Crown Castle International');
insert into stocks_to_scan(id, figi, ticker, name) values (194, null, 'PNC', 'PNC Financial Services Group');
insert into stocks_to_scan(id, figi, ticker, name) values (195, null, 'USB', 'U.S. Bancorp');
insert into stocks_to_scan(id, figi, ticker, name) values (196, null, 'MMC', 'Marsh & McLennan Companies');
insert into stocks_to_scan(id, figi, ticker, name) values (197, null, 'CB', 'Chubb Limited');
insert into stocks_to_scan(id, figi, ticker, name) values (198, null, 'CME', 'CME Group');
insert into stocks_to_scan(id, figi, ticker, name) values (199, null, 'EQIX', 'Equinix');
insert into stocks_to_scan(id, figi, ticker, name) values (200, null, 'ICE', 'Intercontinental Exchange');
insert into stocks_to_scan(id, figi, ticker, name) values (201, null, 'PSA', 'Public Storage');
insert into stocks_to_scan(id, figi, ticker, name) values (202, null, 'AON', 'Aon');
insert into stocks_to_scan(id, figi, ticker, name) values (203, null, 'COF', 'Capital One Financial');
insert into stocks_to_scan(id, figi, ticker, name) values (204, null, 'PGR', 'Progressive');
insert into stocks_to_scan(id, figi, ticker, name) values (205, null, 'MET', 'MetLife');
insert into stocks_to_scan(id, figi, ticker, name) values (206, null, 'SPG', 'Simon Property Group');
insert into stocks_to_scan(id, figi, ticker, name) values (207, null, 'DLR', 'Digital Realty Trust');
insert into stocks_to_scan(id, figi, ticker, name) values (208, null, 'BK', 'The Bank of New York Mellon');
insert into stocks_to_scan(id, figi, ticker, name) values (209, null, 'AIG', 'American International Group');
insert into stocks_to_scan(id, figi, ticker, name) values (210, null, 'TROW', 'T. Rowe Price Group');
insert into stocks_to_scan(id, figi, ticker, name) values (211, null, 'SBAC', 'SBA Communications');
insert into stocks_to_scan(id, figi, ticker, name) values (212, null, 'PRU', 'Prudential Financial');
insert into stocks_to_scan(id, figi, ticker, name) values (213, null, 'O', 'Realty Income');
insert into stocks_to_scan(id, figi, ticker, name) values (214, null, 'SIVB', 'SVB Financial');
insert into stocks_to_scan(id, figi, ticker, name) values (215, null, 'AFL', 'AFLAC Incorporated');
insert into stocks_to_scan(id, figi, ticker, name) values (216, null, 'TRV', 'The Travelers Companies');
insert into stocks_to_scan(id, figi, ticker, name) values (217, null, 'WELL', 'Welltower');
insert into stocks_to_scan(id, figi, ticker, name) values (218, null, 'CBRE', 'CBRE Group');
insert into stocks_to_scan(id, figi, ticker, name) values (219, null, 'AVB', 'AvalonBay Communities');
insert into stocks_to_scan(id, figi, ticker, name) values (220, null, 'FRC', 'FIRST REPUBLIC BANK');
insert into stocks_to_scan(id, figi, ticker, name) values (221, null, 'DFS', 'Discover Financial Services');
insert into stocks_to_scan(id, figi, ticker, name) values (222, null, 'AJG', 'Arthur J. Gallagher & Co');
insert into stocks_to_scan(id, figi, ticker, name) values (223, null, 'ARE', 'Alexandria Real Estate Equities');
insert into stocks_to_scan(id, figi, ticker, name) values (224, null, 'STT', 'State Street');
insert into stocks_to_scan(id, figi, ticker, name) values (225, null, 'GPS', 'Gap, Inc.');
insert into stocks_to_scan(id, figi, ticker, name) values (226, null, 'MSFT', 'Microsoft');
insert into stocks_to_scan(id, figi, ticker, name) values (227, null, 'AMP', 'Ameriprise Financial');
insert into stocks_to_scan(id, figi, ticker, name) values (228, null, 'EQR', 'Equity Residential');
insert into stocks_to_scan(id, figi, ticker, name) values (229, null, 'ALL', 'Allstate');
insert into stocks_to_scan(id, figi, ticker, name) values (230, null, 'NDAQ', 'Nasdaq');
insert into stocks_to_scan(id, figi, ticker, name) values (231, null, 'WY', 'Weyerhaeuser');
insert into stocks_to_scan(id, figi, ticker, name) values (232, null, 'FITB', 'Fifth Third Bancorp');
insert into stocks_to_scan(id, figi, ticker, name) values (233, null, 'EXR', 'Extra Space Storage');
insert into stocks_to_scan(id, figi, ticker, name) values (234, null, 'WLTW', 'Willis Towers Watson Public Limited');
insert into stocks_to_scan(id, figi, ticker, name) values (235, null, 'MAA', 'Mid-America Apartment Communities');
insert into stocks_to_scan(id, figi, ticker, name) values (236, null, 'SYF', 'Synchrony Financial');
insert into stocks_to_scan(id, figi, ticker, name) values (237, null, 'DRE', 'Duke Realty');
insert into stocks_to_scan(id, figi, ticker, name) values (238, null, 'NTRS', 'Northern Trust');
insert into stocks_to_scan(id, figi, ticker, name) values (239, null, 'URI', 'United Rentals');
insert into stocks_to_scan(id, figi, ticker, name) values (240, null, 'HIG', 'Hartford Financial Services Group');
insert into stocks_to_scan(id, figi, ticker, name) values (241, null, 'ESS', 'Essex Property Trust');
insert into stocks_to_scan(id, figi, ticker, name) values (242, null, 'RF', 'Regions Financial');
insert into stocks_to_scan(id, figi, ticker, name) values (243, null, 'RJF', 'Raymond James Financial');
insert into stocks_to_scan(id, figi, ticker, name) values (244, null, 'VTR', 'Ventas');
insert into stocks_to_scan(id, figi, ticker, name) values (245, null, 'CFG', 'Citizens Financial Group');
insert into stocks_to_scan(id, figi, ticker, name) values (246, null, 'MTB', 'M&T Bank');
insert into stocks_to_scan(id, figi, ticker, name) values (247, null, 'PEAK', 'Healthpeak Properties');
insert into stocks_to_scan(id, figi, ticker, name) values (248, null, 'BRO', 'Brown & Brown');
insert into stocks_to_scan(id, figi, ticker, name) values (249, null, 'PFG', 'Principal Financial Group');
insert into stocks_to_scan(id, figi, ticker, name) values (250, null, 'SBNY', 'Signature Bank');
insert into stocks_to_scan(id, figi, ticker, name) values (251, null, 'UDR', 'UDR');
insert into stocks_to_scan(id, figi, ticker, name) values (252, null, 'CINF', 'Cincinnati Financial');
insert into stocks_to_scan(id, figi, ticker, name) values (253, null, 'BXP', 'Boston Properties,');
insert into stocks_to_scan(id, figi, ticker, name) values (254, null, 'BEN', 'Franklin Resources');
insert into stocks_to_scan(id, figi, ticker, name) values (255, null, 'KIN', 'Kimco Realty');
insert into stocks_to_scan(id, figi, ticker, name) values (256, null, 'IRM', 'Iron Mountain');
insert into stocks_to_scan(id, figi, ticker, name) values (257, null, 'MKTX', 'MarketAxess');
insert into stocks_to_scan(id, figi, ticker, name) values (258, null, 'L', 'Loews');
insert into stocks_to_scan(id, figi, ticker, name) values (259, null, 'WRB', 'W.R. Berkley');
insert into stocks_to_scan(id, figi, ticker, name) values (260, null, 'CBOE', 'Cboe Global Markets');
insert into stocks_to_scan(id, figi, ticker, name) values (261, null, 'REG', 'Regency Centers');
insert into stocks_to_scan(id, figi, ticker, name) values (262, null, 'LNC', 'Lincoln National');
insert into stocks_to_scan(id, figi, ticker, name) values (263, null, 'HST', 'Host Hotels');
insert into stocks_to_scan(id, figi, ticker, name) values (264, null, 'CMA', 'Comerica');
insert into stocks_to_scan(id, figi, ticker, name) values (265, null, 'IVZ', 'Invesco');
insert into stocks_to_scan(id, figi, ticker, name) values (266, null, 'RE', 'Everest Re Group');
insert into stocks_to_scan(id, figi, ticker, name) values (267, null, 'FRT', 'Federal Realty Investment');
insert into stocks_to_scan(id, figi, ticker, name) values (268, null, 'ZION', 'Zions Bancorporation');
insert into stocks_to_scan(id, figi, ticker, name) values (269, null, 'GL', 'Globe Life');
insert into stocks_to_scan(id, figi, ticker, name) values (270, null, 'AIZ', 'Assurant');
insert into stocks_to_scan(id, figi, ticker, name) values (271, null, 'VNO', 'Vornado Realty Trust');
insert into stocks_to_scan(id, figi, ticker, name) values (272, null, 'PBCT', 'People’s');
insert into stocks_to_scan(id, figi, ticker, name) values (273, null, 'UNH', 'UnitedHealth Group');
insert into stocks_to_scan(id, figi, ticker, name) values (274, null, 'ANTM', 'Anthem');
insert into stocks_to_scan(id, figi, ticker, name) values (275, null, 'HCA', 'HCA Healthcare');
insert into stocks_to_scan(id, figi, ticker, name) values (276, null, 'CI', 'Cigna');
insert into stocks_to_scan(id, figi, ticker, name) values (277, null, 'HUM', 'Humana');
insert into stocks_to_scan(id, figi, ticker, name) values (278, null, 'IQV', 'IQVIA Holdings');
insert into stocks_to_scan(id, figi, ticker, name) values (279, null, 'LH', 'Laboratory Corporation of America Holdings');
insert into stocks_to_scan(id, figi, ticker, name) values (280, null, 'DGX', 'Quest Diagnostics');
insert into stocks_to_scan(id, figi, ticker, name) values (281, null, 'DVA', 'DaVita');
insert into stocks_to_scan(id, figi, ticker, name) values (282, null, 'UHS', 'Universal Health Services');
insert into stocks_to_scan(id, figi, ticker, name) values (283, null, 'JNJ', 'Johnson & Johnson');
insert into stocks_to_scan(id, figi, ticker, name) values (284, null, 'PFE', 'Pfizer');
insert into stocks_to_scan(id, figi, ticker, name) values (285, null, 'LLY', 'Eli Lilly and Company');
insert into stocks_to_scan(id, figi, ticker, name) values (286, null, 'TMO', 'Thermo Fisher Scientific');
insert into stocks_to_scan(id, figi, ticker, name) values (287, null, 'ABT', 'Abbott Laboratories');
insert into stocks_to_scan(id, figi, ticker, name) values (288, null, 'ABBV', 'AbbVie');
insert into stocks_to_scan(id, figi, ticker, name) values (289, null, 'DHR', 'Danaher');
insert into stocks_to_scan(id, figi, ticker, name) values (290, null, 'MRK', 'Merck & Company');
insert into stocks_to_scan(id, figi, ticker, name) values (291, null, 'MDT', 'Medtronic');
insert into stocks_to_scan(id, figi, ticker, name) values (292, null, 'BMY', 'Bristol-Myers Squibb');
insert into stocks_to_scan(id, figi, ticker, name) values (293, null, 'ISRG', 'Intuitive Surgical');
insert into stocks_to_scan(id, figi, ticker, name) values (294, null, 'AMGN', 'Amgen');
insert into stocks_to_scan(id, figi, ticker, name) values (295, null, 'ZTS', 'Zoetis');
insert into stocks_to_scan(id, figi, ticker, name) values (296, null, 'SYK', 'Stryker');
insert into stocks_to_scan(id, figi, ticker, name) values (297, null, 'MRNA', 'Moderna');
insert into stocks_to_scan(id, figi, ticker, name) values (298, null, 'GILD', 'Gilead Sciences');
insert into stocks_to_scan(id, figi, ticker, name) values (299, null, 'EW', 'Edwards Lifesciences ');
insert into stocks_to_scan(id, figi, ticker, name) values (300, null, 'BDX', 'Becton, Dickinson and Company');
insert into stocks_to_scan(id, figi, ticker, name) values (301, null, 'REGN', 'Regeneron Pharmaceuticals');
insert into stocks_to_scan(id, figi, ticker, name) values (302, null, 'BSX', 'Boston Scientific');
insert into stocks_to_scan(id, figi, ticker, name) values (303, null, 'ILMN', 'Illumina');
insert into stocks_to_scan(id, figi, ticker, name) values (304, null, 'VRTX', 'Vertex Pharmaceuticals');
insert into stocks_to_scan(id, figi, ticker, name) values (305, null, 'IDXX', 'IDEXX Laboratories');
insert into stocks_to_scan(id, figi, ticker, name) values (306, null, 'ALGN', 'Align Technology');
insert into stocks_to_scan(id, figi, ticker, name) values (307, null, 'DXCM', 'DexCom');
insert into stocks_to_scan(id, figi, ticker, name) values (308, null, 'A', 'Agilent');
insert into stocks_to_scan(id, figi, ticker, name) values (309, null, 'BAX', 'Baxter');
insert into stocks_to_scan(id, figi, ticker, name) values (310, null, 'MTD', 'Mettler-Toledo');
insert into stocks_to_scan(id, figi, ticker, name) values (311, null, 'RMD', 'ResMed');
insert into stocks_to_scan(id, figi, ticker, name) values (312, null, 'WST', 'West Pharmaceutical Services');
insert into stocks_to_scan(id, figi, ticker, name) values (313, null, 'ZBH', 'Zimmer Biomet Holdings');
insert into stocks_to_scan(id, figi, ticker, name) values (314, null, 'STE', 'STERIS');
insert into stocks_to_scan(id, figi, ticker, name) values (315, null, 'PKI', 'PerkinElmer');
insert into stocks_to_scan(id, figi, ticker, name) values (316, null, 'WAT', 'Waters Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (317, null, 'BIO', 'Bio-Rad Laboratories');
insert into stocks_to_scan(id, figi, ticker, name) values (318, null, 'CTLT', 'Catalent');
insert into stocks_to_scan(id, figi, ticker, name) values (319, null, 'COO', 'The Cooper Companies,');
insert into stocks_to_scan(id, figi, ticker, name) values (320, null, 'TECH', 'Bio-Techne');
insert into stocks_to_scan(id, figi, ticker, name) values (321, null, 'HOLX', 'Hologic');
insert into stocks_to_scan(id, figi, ticker, name) values (322, null, 'VTRS', 'Viatris');
insert into stocks_to_scan(id, figi, ticker, name) values (323, null, 'ABMD', 'ABIOMED');
insert into stocks_to_scan(id, figi, ticker, name) values (324, null, 'INCY', 'Incyte');
insert into stocks_to_scan(id, figi, ticker, name) values (325, null, 'TFX', 'Teleflex');
insert into stocks_to_scan(id, figi, ticker, name) values (326, null, 'XRAY', 'DENTSPLY SIRONA');
insert into stocks_to_scan(id, figi, ticker, name) values (327, null, 'OGN', 'Organon & Co');
insert into stocks_to_scan(id, figi, ticker, name) values (328, null, 'WM', 'Waste Management');
insert into stocks_to_scan(id, figi, ticker, name) values (329, null, 'SLB', 'Schlumberger');
insert into stocks_to_scan(id, figi, ticker, name) values (330, null, 'RSG', 'Republic Services');
insert into stocks_to_scan(id, figi, ticker, name) values (331, null, 'KMI', 'Kinder Morgan');
insert into stocks_to_scan(id, figi, ticker, name) values (332, null, 'WMB', 'Williams Companies');
insert into stocks_to_scan(id, figi, ticker, name) values (333, null, 'OKE', 'ONEOK');
insert into stocks_to_scan(id, figi, ticker, name) values (334, null, 'BKR', 'Baker Hughes');
insert into stocks_to_scan(id, figi, ticker, name) values (335, null, 'HAL', 'Halliburton');
insert into stocks_to_scan(id, figi, ticker, name) values (336, null, 'J', 'Jacobs Engineering Group');
insert into stocks_to_scan(id, figi, ticker, name) values (337, null, 'PWR', 'Quanta Services');
insert into stocks_to_scan(id, figi, ticker, name) values (338, null, 'FCX', 'Freeport-McMoRan');
insert into stocks_to_scan(id, figi, ticker, name) values (339, null, 'NEM', 'Newmont');
insert into stocks_to_scan(id, figi, ticker, name) values (340, null, 'NUE', 'Nucor');
insert into stocks_to_scan(id, figi, ticker, name) values (341, null, 'VMC', 'Vulcan Materials Company');
insert into stocks_to_scan(id, figi, ticker, name) values (342, null, 'MLM', 'Martin Marietta Materials');
insert into stocks_to_scan(id, figi, ticker, name) values (343, null, 'LIN', 'Linde');
insert into stocks_to_scan(id, figi, ticker, name) values (344, null, 'SHW', 'Sherwin-Williams');
insert into stocks_to_scan(id, figi, ticker, name) values (345, null, 'ECL', 'Ecolab');
insert into stocks_to_scan(id, figi, ticker, name) values (346, null, 'APD', 'Air Products and Chemicals');
insert into stocks_to_scan(id, figi, ticker, name) values (347, null, 'DOW', 'Dow');
insert into stocks_to_scan(id, figi, ticker, name) values (348, null, 'DD', 'DuPont de Nemours');
insert into stocks_to_scan(id, figi, ticker, name) values (349, null, 'PPG', 'PPG Industries');
insert into stocks_to_scan(id, figi, ticker, name) values (350, null, 'ADM', 'Archer-Daniels-Midland');
insert into stocks_to_scan(id, figi, ticker, name) values (351, null, 'CTVA', 'Corteva');
insert into stocks_to_scan(id, figi, ticker, name) values (352, null, 'LYB', 'LyondellBasell Industries');
insert into stocks_to_scan(id, figi, ticker, name) values (353, null, 'BLL', 'Ball Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (354, null, 'ALB', 'Albemarle');
insert into stocks_to_scan(id, figi, ticker, name) values (355, null, 'CE', 'Celanese Corporation Celanese');
insert into stocks_to_scan(id, figi, ticker, name) values (356, null, 'AMCR', 'Amcor');
insert into stocks_to_scan(id, figi, ticker, name) values (357, null, 'IP', 'International Paper ');
insert into stocks_to_scan(id, figi, ticker, name) values (358, null, 'AVY', 'Avery Dennison');
insert into stocks_to_scan(id, figi, ticker, name) values (359, null, 'EMN', 'Eastman Chemical ');
insert into stocks_to_scan(id, figi, ticker, name) values (360, null, 'MOS', 'Mosaic');
insert into stocks_to_scan(id, figi, ticker, name) values (361, null, 'CF', 'CF Industries');
insert into stocks_to_scan(id, figi, ticker, name) values (362, null, 'FMC', 'FMC');
insert into stocks_to_scan(id, figi, ticker, name) values (363, null, 'PKG', 'Packaging Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (364, null, 'WRK', 'Westrock');
insert into stocks_to_scan(id, figi, ticker, name) values (365, null, 'SEE', 'Sealed Air');
insert into stocks_to_scan(id, figi, ticker, name) values (366, null, 'HON', 'Honeywell');
insert into stocks_to_scan(id, figi, ticker, name) values (367, null, 'AMAT', 'Applied Materials');
insert into stocks_to_scan(id, figi, ticker, name) values (368, null, 'CAT', 'Caterpillar');
insert into stocks_to_scan(id, figi, ticker, name) values (369, null, 'DE', 'Deere & Company');
insert into stocks_to_scan(id, figi, ticker, name) values (370, null, 'GE', 'General Electric');
insert into stocks_to_scan(id, figi, ticker, name) values (371, null, 'MMM', '3M');
insert into stocks_to_scan(id, figi, ticker, name) values (372, null, 'ITW', 'Illinois Tool Works');
insert into stocks_to_scan(id, figi, ticker, name) values (373, null, 'ETN', 'Eaton Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (374, null, 'JCI', 'Johnson Controls');
insert into stocks_to_scan(id, figi, ticker, name) values (375, null, 'EMR', 'Emerson Electric');
insert into stocks_to_scan(id, figi, ticker, name) values (376, null, 'TT', 'Trane Technologies ');
insert into stocks_to_scan(id, figi, ticker, name) values (377, null, 'CARR', 'Carrier Global');
insert into stocks_to_scan(id, figi, ticker, name) values (378, null, 'APTV', 'Aptiv PLC');
insert into stocks_to_scan(id, figi, ticker, name) values (379, null, 'PH', 'Parker-Hannifin');
insert into stocks_to_scan(id, figi, ticker, name) values (380, null, 'ROK', 'Rockwell Automation');
insert into stocks_to_scan(id, figi, ticker, name) values (381, null, 'OTIS', 'Otis Worldwide');
insert into stocks_to_scan(id, figi, ticker, name) values (382, null, 'AME', 'AMETEK');
insert into stocks_to_scan(id, figi, ticker, name) values (383, null, 'CMI', 'Cummins');
insert into stocks_to_scan(id, figi, ticker, name) values (384, null, 'PCAR', 'PACCAR');
insert into stocks_to_scan(id, figi, ticker, name) values (385, null, 'DOV', 'Dover');
insert into stocks_to_scan(id, figi, ticker, name) values (386, null, 'IR', 'Ingersoll Rand');
insert into stocks_to_scan(id, figi, ticker, name) values (387, null, 'GNRC', 'Generac Holdlings');
insert into stocks_to_scan(id, figi, ticker, name) values (388, null, 'XYL', 'Xylem');
insert into stocks_to_scan(id, figi, ticker, name) values (389, null, 'IEX', 'IDEX');
insert into stocks_to_scan(id, figi, ticker, name) values (390, null, 'WAB', 'Westinghouse Air Brake Technologies');
insert into stocks_to_scan(id, figi, ticker, name) values (391, null, 'MAS', 'Masco');
insert into stocks_to_scan(id, figi, ticker, name) values (392, null, 'SEDG', 'SolarEdge Technologies');
insert into stocks_to_scan(id, figi, ticker, name) values (393, null, 'FBHS', 'Fortune Brands Home & Security');
insert into stocks_to_scan(id, figi, ticker, name) values (394, null, 'AOS', 'A.O. Smith');
insert into stocks_to_scan(id, figi, ticker, name) values (395, null, 'PNR', 'Pentair');
insert into stocks_to_scan(id, figi, ticker, name) values (396, null, 'ALLE', 'Allegion');
insert into stocks_to_scan(id, figi, ticker, name) values (397, null, 'BWA', 'BorgWarner');
insert into stocks_to_scan(id, figi, ticker, name) values (398, null, 'NWL', 'Newell Brands');
insert into stocks_to_scan(id, figi, ticker, name) values (399, null, 'AMZN', 'Amazon');
insert into stocks_to_scan(id, figi, ticker, name) values (400, null, 'HD', 'Home Depot');
insert into stocks_to_scan(id, figi, ticker, name) values (401, null, 'WMT', 'Walmart');
insert into stocks_to_scan(id, figi, ticker, name) values (402, null, 'COST', 'Costco Wholesale');
insert into stocks_to_scan(id, figi, ticker, name) values (403, null, 'LOW', 'Lowe’s Companies');
insert into stocks_to_scan(id, figi, ticker, name) values (404, null, 'CVS', 'CVS Health Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (405, null, 'TGT', 'Target Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (406, null, 'GOOG', 'Alphabet');
insert into stocks_to_scan(id, figi, ticker, name) values (407, null, 'GOOGL', 'Alphabet');
insert into stocks_to_scan(id, figi, ticker, name) values (408, null, 'FB', 'Meta Platforms');
insert into stocks_to_scan(id, figi, ticker, name) values (409, null, 'ACN', 'Accenture');
insert into stocks_to_scan(id, figi, ticker, name) values (410, null, 'CSCO', 'Cisco');
insert into stocks_to_scan(id, figi, ticker, name) values (411, null, 'NFLX', 'Netflix');
insert into stocks_to_scan(id, figi, ticker, name) values (412, null, 'CRM', 'Salesforce.com');
insert into stocks_to_scan(id, figi, ticker, name) values (413, null, 'ORCL', 'Oracle');
insert into stocks_to_scan(id, figi, ticker, name) values (414, null, 'PYPL', 'PayPal');
insert into stocks_to_scan(id, figi, ticker, name) values (415, null, 'INTU', 'Intuit');
insert into stocks_to_scan(id, figi, ticker, name) values (416, null, 'NOW', 'ServiceNow');
insert into stocks_to_scan(id, figi, ticker, name) values (417, null, 'IBM', 'International Business Machines');
insert into stocks_to_scan(id, figi, ticker, name) values (418, null, 'ADP', 'Automatic Data Processing');
insert into stocks_to_scan(id, figi, ticker, name) values (419, null, 'FISV', 'Fiserv');
insert into stocks_to_scan(id, figi, ticker, name) values (420, null, 'FIS', 'Fidelity National Information');
insert into stocks_to_scan(id, figi, ticker, name) values (421, null, 'ADSK', 'Autodesk');
insert into stocks_to_scan(id, figi, ticker, name) values (422, null, 'SNPS', 'Synopsys');
insert into stocks_to_scan(id, figi, ticker, name) values (423, null, 'INFO', 'IHS Marki');
insert into stocks_to_scan(id, figi, ticker, name) values (424, null, 'CDNS', 'Cadence Design Systems');
insert into stocks_to_scan(id, figi, ticker, name) values (425, null, 'ROP', 'Roper Technologies,');
insert into stocks_to_scan(id, figi, ticker, name) values (426, null, 'MSCI', 'MSCI');
insert into stocks_to_scan(id, figi, ticker, name) values (427, null, 'PAYX', 'Paychex');
insert into stocks_to_scan(id, figi, ticker, name) values (428, null, 'CTSH', 'Cognizant Technology Solutions');
insert into stocks_to_scan(id, figi, ticker, name) values (429, null, 'GPN', 'Global Payments');
insert into stocks_to_scan(id, figi, ticker, name) values (430, null, 'MTCH', 'Match Group');
insert into stocks_to_scan(id, figi, ticker, name) values (431, null, 'EPAM', 'EPAM Systems');
insert into stocks_to_scan(id, figi, ticker, name) values (432, null, 'VRSK', 'Verisk Analytics');
insert into stocks_to_scan(id, figi, ticker, name) values (433, null, 'ANSS', 'ANSYS');
insert into stocks_to_scan(id, figi, ticker, name) values (434, null, 'TWTR', 'Twitter');
insert into stocks_to_scan(id, figi, ticker, name) values (435, null, 'VRSN', 'VeriSign');
insert into stocks_to_scan(id, figi, ticker, name) values (436, null, 'CDW', 'CDW');
insert into stocks_to_scan(id, figi, ticker, name) values (437, null, 'CERN', 'Cerner');
insert into stocks_to_scan(id, figi, ticker, name) values (438, null, 'IT', 'Gartner');
insert into stocks_to_scan(id, figi, ticker, name) values (439, null, 'PAYC', 'Paycom Software');
insert into stocks_to_scan(id, figi, ticker, name) values (440, null, 'TYL', 'Tyler Technologies');
insert into stocks_to_scan(id, figi, ticker, name) values (441, null, 'BR', 'Broadridge Financial Solutions');
insert into stocks_to_scan(id, figi, ticker, name) values (442, null, 'AKAM', 'Akamai Technologies');
insert into stocks_to_scan(id, figi, ticker, name) values (443, null, 'FDS', 'FactSet Research Systems');
insert into stocks_to_scan(id, figi, ticker, name) values (444, null, 'CDAY', 'Ceridian HCM Holding');
insert into stocks_to_scan(id, figi, ticker, name) values (445, null, 'NLOK', 'NortonLifeLock');
insert into stocks_to_scan(id, figi, ticker, name) values (446, null, 'PTC', 'PTC');
insert into stocks_to_scan(id, figi, ticker, name) values (447, null, 'JKHY', 'Jack Henry & Associates');
insert into stocks_to_scan(id, figi, ticker, name) values (448, null, 'LDOS', 'Leidos Holdings');
insert into stocks_to_scan(id, figi, ticker, name) values (449, null, 'CTXS', 'Citrix Systems');
insert into stocks_to_scan(id, figi, ticker, name) values (450, null, 'JNPR', 'Juniper Networks');
insert into stocks_to_scan(id, figi, ticker, name) values (451, null, 'DXC', 'DXC Technology');
insert into stocks_to_scan(id, figi, ticker, name) values (452, null, 'UPS', 'United Parcel Service');
insert into stocks_to_scan(id, figi, ticker, name) values (453, null, 'UNP', 'Union Pacific Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (454, null, 'CSX', 'CSX Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (455, null, 'FDX', 'FedEx');
insert into stocks_to_scan(id, figi, ticker, name) values (456, null, 'ODFL', 'Old Dominion Freight Line');
insert into stocks_to_scan(id, figi, ticker, name) values (457, null, 'LUV', 'Southwest Airlines Company');
insert into stocks_to_scan(id, figi, ticker, name) values (458, null, 'DAL', 'Delta Air Lines');
insert into stocks_to_scan(id, figi, ticker, name) values (459, null, 'PANW', 'Palo alto Networks');
insert into stocks_to_scan(id, figi, ticker, name) values (460, null, 'EXPD', 'Expeditors International of Washington');
insert into stocks_to_scan(id, figi, ticker, name) values (461, null, 'JBHT', 'J.B. Hunt Transport Services');
insert into stocks_to_scan(id, figi, ticker, name) values (462, null, 'UAL', 'United Airlines Holdings');
insert into stocks_to_scan(id, figi, ticker, name) values (463, null, 'CHRW', 'C.H. Robinson Worldwide');
insert into stocks_to_scan(id, figi, ticker, name) values (464, null, 'AAL', 'American Airlines Group');
insert into stocks_to_scan(id, figi, ticker, name) values (465, null, 'ALK', 'Alaska Air Group');
insert into stocks_to_scan(id, figi, ticker, name) values (466, null, 'NEE', 'NextEra Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (467, null, 'DUK', 'Duke Energy Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (468, null, 'SO', 'Southern Company');
insert into stocks_to_scan(id, figi, ticker, name) values (469, null, 'D', 'Dominion Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (470, null, 'EXC', 'Exelon Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (471, null, 'AEP', 'American Electric Power Company');
insert into stocks_to_scan(id, figi, ticker, name) values (472, null, 'SRE', 'DBA Sempra');
insert into stocks_to_scan(id, figi, ticker, name) values (473, null, 'XEL', 'Xcel Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (474, null, 'PEG', 'Public Service Enterprise Group');
insert into stocks_to_scan(id, figi, ticker, name) values (475, null, 'AWK', 'American Water Works Company');
insert into stocks_to_scan(id, figi, ticker, name) values (476, null, 'ES', 'Eversource Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (477, null, 'WEC', 'WEC Energy Group');
insert into stocks_to_scan(id, figi, ticker, name) values (478, null, 'ED', 'Consolidated Edison');
insert into stocks_to_scan(id, figi, ticker, name) values (4&9, null, 'EIX', 'Edison International');
insert into stocks_to_scan(id, figi, ticker, name) values (480, null, 'DTE', 'DTE Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (481, null, 'AEE', 'Ameren');
insert into stocks_to_scan(id, figi, ticker, name) values (482, null, 'PPL', 'PPL');
insert into stocks_to_scan(id, figi, ticker, name) values (483, null, 'FE', 'FirstEnergy');
insert into stocks_to_scan(id, figi, ticker, name) values (484, null, 'SPOT', 'Spotify');
insert into stocks_to_scan(id, figi, ticker, name) values (485, null, 'ETR', 'Entergy');
insert into stocks_to_scan(id, figi, ticker, name) values (486, null, 'CMS', 'CMS Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (487, null, 'CNP', 'CenterPoint Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (488, null, 'AES', 'The AES Corporation');
insert into stocks_to_scan(id, figi, ticker, name) values (489, null, 'EVRG', 'Evergy');
insert into stocks_to_scan(id, figi, ticker, name) values (490, null, 'LNT', 'Alliant Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (491, null, 'ATO', 'Atmos Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (492, null, 'NI', 'NiSource');
insert into stocks_to_scan(id, figi, ticker, name) values (493, null, 'NRG', 'NRG Energy');
insert into stocks_to_scan(id, figi, ticker, name) values (494, null, 'PNW', 'Pinnacle West Capital');